### ISSUE TITLE
Create MysqlCluster Failed

### ISSUE THREAD

**Issue by luoyangustc** [bitpoke/mysql-operator#614]
When I use mysql-operator/charts/mysql-cluster to generate the mysql-cluster.yaml,The content show as follow:
```yaml
apiVersion: mysql.presslabs.org/v1alpha1
kind: MysqlCluster
metadata:
  name: mysql-cluster-db
  labels:
    app: mysql-cluster
    chart: mysql-cluster-0.3.0
    release: mysql-cluster
    heritage: Tiller
spec:
  replicas: 3
  secretName: mysql-cluster-db
  volumeSpec:
    hostPath:
      path: /tmp
      type: DirectoryOrCreate
```

The result :
![image](https://user-images.githubusercontent.com/31932405/96414355-96e7ec80-121f-11eb-9ee0-d2e4b12e3c12.png)
The pod of mysql-cluster-db-mysql-0 is Ok,but mysql-cluster-db-mysql-1 is Error.
kubectl logs mysql-cluster-db-mysql-1 -c init:
![image](https://user-images.githubusercontent.com/31932405/96414515-ce569900-121f-11eb-9b2b-fc8bee2e916f.png)

what should i do !I need Help so much!
Thanks a lot!
