### ISSUE TITLE
Issues starting new clusters with backups

### ISSUE THREAD

**Issue by mjpitz** [bitpoke/mysql-operator#623]
My configuration seems pretty straight forward but my cluster isn't starting for what looks like permissions issues

```
020-10-28T17:46:04.777011213Z  ERROR   sidecar clone command failed    {"error": "removing lost+found: openfdat /var/lib/mysql/lost+found: permission denied"}
```

I tried enabling the volume permission container but that doesn't do anything since it's last in the chain and never gets a chance to run. Can someone help me understand why my cluster won't start?

```
---
apiVersion: mysql.presslabs.org/v1alpha1
kind: MysqlCluster
metadata:
  namespace: xxx
  name: xxx
spec:
  replicas: 2
  secretName: xxx

  backupSchedule: "0 0 * * *"
  backupURL: s3://backups/xxx/
  backupSecretName: xxx-backup
  backupRemoteDeletePolicy: retain

  podSpec:
    resources:
      requests:
        cpu: 500m
        memory: 1Gi
      limits:
        cpu: 500m
        memory: 1Gi
    initContainers:
      - name: volume-permissions
        image: busybox
        securityContext:
          runAsUser: 0
        command:
          - sh
          - -c
          - chmod 750 /data/mysql; chown 999:999 /data/mysql
        volumeMounts:
          - name: data
            mountPath: /data/mysql
  volumeSpec:
    persistentVolumeClaim:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 5Gi
```
