### ISSUE TITLE
Use tagged versions in the Helm chart

### ISSUE THREAD

**Issue by sagikazarmark** [bitpoke/mysql-operator#677]
Hey there! Thanks a lot for this operator!

Currently the Helm chart installs the operator with `latest` image tags. I don't think this is a good practice (especially with the image pull policy defaulting to `IfNotPresent`).

I'd suggest using the operator version in the chart as image version by default in the next release.

For example, I'm using these values at the moment:

```yaml
image: quay.io/presslabs/mysql-operator:0.4.0
sidecarImage: quay.io/presslabs/mysql-operator-sidecar-mysql57:v0.4.0-113-g31d1e211

orchestrator:
  image: quay.io/presslabs/mysql-operator-orchestrator:0.4.0

```
