### ISSUE TITLE
root user login failed

### ISSUE THREAD

**Issue by clcc2019** [bitpoke/mysql-operator#764]
<img width="497" alt="image" src="https://user-images.githubusercontent.com/46099295/142819894-9dd46d5a-f0b8-44c4-8bfd-dbde060614f8.png">

**Comment by clcc2019** [comment]
<img width="1165" alt="image" src="https://user-images.githubusercontent.com/46099295/142823096-13da3d0c-51e2-4cb4-b6c2-4207745683b9.png">
<img width="1279" alt="image" src="https://user-images.githubusercontent.com/46099295/142823233-844254df-e94b-4d1d-b043-11aab69ae8df.png">
<img width="911" alt="image" src="https://user-images.githubusercontent.com/46099295/142823292-b033c98a-4ff6-4502-aa49-64d90d992bea.png">

use sys_replication user login success

<img width="1491" alt="image" src="https://user-images.githubusercontent.com/46099295/142823446-1ffb1b76-e1dd-4397-8b13-79296fd5f74c.png">

**Comment by calind** [comment]
Can you give the steps used to deploy so we can test. Thanks!

**Comment by clcc2019** [comment]
> Can you give the steps used to deploy so we can test. Thanks!

1、use helm v3 install operator v0.5.1
2、Then install mysql cluster


helm. values.yaml
```yaml
# Default values for mysql-operator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicas: 3
image: docker.io/bitpoke/mysql-operator:v0.5.1
sidecarImage: docker.io/bitpoke/mysql-operator-sidecar-8.0:v0.5.1
sidecarMysql8Image: docker.io/bitpoke/mysql-operator-sidecar-8.0:v0.5.1
imagePullPolicy: IfNotPresent
# Insert a pre-stop lifecycle hook and trigger a failover. NOTE: Use this when your cluster network
# policy allows to connect across namespaces and the mysql node is able to connecto to operator pod
gracefulShutdown:
  enabled: false
imagePullSecrets:
# - name: "image-pull-secret"

# whether or not to install CRDs
installCRDs: true
# in which namespace to watch for resource, leave empty to watch in all namespaces
watchNamespace:
# The operator will install a ServiceMonitor if you have prometheus-operator installed.
serviceMonitor:
  enabled: true
  ## Additional labels for the serviceMonitor. Useful if you have multiple prometheus operators running to select only specific ServiceMonitors
  # additionalLabels:
  #   prometheus: prom-internal
  interval: 10s
  scrapeTimeout: 3s
  # jobLabel:
  # targetLabels:
  # podTargetLabels:
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      app.kubernetes.io/managed-by: mysql.presslabs.org
      app.kubernetes.io/name: mysql
nodeSelector: {}
tolerations: []
resources: {}
# limits:
#  cpu: 100m
#  memory: 128Mi
# requests:
#  cpu: 100m
#  memory: 128Mi

securityContext:
  runAsNonRoot: true
  # 65532 is the UID for nonroot user from distroless image
  runAsUser: 65532
  runAsGroup: 65532
  fsGroup: 65532
## nodeAffinity settings
# nodeAffinity:
#   requiredDuringSchedulingIgnoredDuringExecution:
#     nodeSelectorTerms:
#     - matchExpressions:
#       - key: cloud.google.com/gke-preemptible
#         operator: NotIn
#         values:
#         - true

## Anti-Affinity setting. The default "hard" will use pod anti-affinity that is
## requiredDuringSchedulingIgnoredDuringExecution to ensure 2 services don't
## end up on the same node. Setting this to "soft" will use
## preferredDuringSchedulingIgnoredDuringExecution. If set to anything else,
## no anti-affinity rules will be configured.
antiAffinity: "none"
extraArgs: []
podDisruptionBudget:
  enabled: true
  maxUnavailable: 1
podSecurityPolicy:
  enabled: false
  annotations:
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: 'docker/default'
    seccomp.security.alpha.kubernetes.io/defaultProfileName: 'docker/default'
rbac:
  create: true
  # if rbac is false this service account is used
  serviceAccountName: default
orchestrator:
  image: docker.io/bitpoke/mysql-operator-orchestrator:v0.5.1
  # orchestrator user and password to manage MySQL clusters
  topologyUser: orchestrator
  topologyPassword: # this is empty and will be random generated if not specified
  # secretName:  # you can specify which secret to use for orchestrator topology credentials
  resources:
  # For example
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi
  service:
    type: ClusterIP
    port: 80
    # nodePort: 3000
  ingress:
    enabled: false
    annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
    hosts:
      - host: chart-example.local
        paths: []
    tls: []
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.local
  persistence:
    enabled: true
    ## If defined, storageClassName: <storageClass>
    ## If set to "-", storageClassName: "", which disables dynamic provisioning
    ## If undefined (the default) or set to null, no storageClassName spec is
    ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
    ##   GKE, AWS & OpenStack)
    ##
    storageClass: "local-path"
    accessMode: "ReadWriteOnce"
    size: 5Gi
    # inject an init container which properly sets the ownership for the orchestrator's data volume
    # this is needed when the PV provisioner does not properly sets permissions for fsGroup
    # when enabling this, you MUST change the securityContext.runAsNonRoot to false
    fsGroupWorkaroundEnabled: false
  # key value map of orchestrator conf directives.
  # see: https://github.com/github/orchestrator/blob/master/conf/orchestrator-sample.conf.json
  # the following keys are manages and thus cannot be overwritten:
  #   - ListenAddress :3000
  #   - MySQLTopologyCredentialsConfigFile /orchestrator/conf/orc-topology.cnf
  #   - BackendDB sqlite
  #   - SQLite3DataFile /var/lib/orchestrator/orc.db
  #   - RaftEnabled true
  #   - RaftDataDir /var/lib/orchestrator
  #   - RaftBind $HOSTNAME
  #   - RaftNodes The statefullset members
  config:
    Debug: false
    # the operator is handling the registries, do not auto discover
    DiscoverByShowSlaveHosts: false
    # forget missing instances automatically
    UnseenInstanceForgetHours: 1
    InstancePollSeconds: 5
    HostnameResolveMethod: "none"
    MySQLHostnameResolveMethod: "@@report_host"
    RemoveTextFromHostnameDisplay: ":3306"
    DetectClusterAliasQuery: "SELECT CONCAT(SUBSTRING(@@hostname, 1, LENGTH(@@hostname) - 1 - LENGTH(SUBSTRING_INDEX(@@hostname,'-',-2))),'.',SUBSTRING_INDEX(@@report_host,'.',-1))"
    DetectInstanceAliasQuery: "SELECT @@hostname"
    SlaveLagQuery: "SELECT TIMESTAMPDIFF(SECOND,ts,UTC_TIMESTAMP()) as drift FROM sys_operator.heartbeat ORDER BY drift ASC LIMIT 1"
    # Automated recovery (this is opt-in, so we need to set these)
    # Prevent recovery flip-flop, by disabling auto-recovery for 5 minutes per
    # cluster
    RecoveryPeriodBlockSeconds: 300
    # Do not ignore any host for auto-recovery
    RecoveryIgnoreHostnameFilters: []
    # Recover both, masters and intermediate masters
    RecoverMasterClusterFilters: ['.*']
    RecoverIntermediateMasterClusterFilters: ['.*']
    # `reset slave all` and `set read_only=0` on promoted master
    ApplyMySQLPromotionAfterMasterFailover: true
    # https://github.com/github/orchestrator/blob/master/docs/configuration-recovery.md#promotion-actions
    # Safety! do not disable unless you know what you are doing
    FailMasterPromotionIfSQLThreadNotUpToDate: true
    DetachLostReplicasAfterMasterFailover: true
    # set downtime on the failed master
    MasterFailoverLostInstancesDowntimeMinutes: 10
    # orchestrator hooks called in the following order
    # for more information about template: https://github.com/github/orchestrator/blob/master/go/logic/topology_recovery.go#L256
    ProcessesShellCommand: "sh"
    OnFailureDetectionProcesses:
      - "/usr/local/bin/orc-helper event -w '{failureClusterAlias}' 'OrcFailureDetection' 'Failure: {failureType}, failed host: {failedHost}, lost replcas: {lostReplicas}' || true"
      - "/usr/local/bin/orc-helper failover-in-progress '{failureClusterAlias}' '{failureDescription}' || true"
    # PreGracefulTakeoverProcesses:
    PreFailoverProcesses:
      # as backup in case the first request fails
      - "/usr/local/bin/orc-helper failover-in-progress '{failureClusterAlias}' '{failureDescription}' || true"
    # PostFailoverProcesses:
    #   - "/usr/local/bin/orchestrator-helper event '{failureClusterAlias}' 'Orc{command}' 'Failure type: {failureType}, failed hosts: {failedHost}, slaves: {countSlaves}' || true"

    PostUnsuccessfulFailoverProcesses:
      - "/usr/local/bin/orc-helper event -w '{failureClusterAlias}' 'OrcPostUnsuccessfulFailover' 'Failure: {failureType}, failed host: {failedHost} with {countSlaves} slaves' || true"
    PostMasterFailoverProcesses:
      - "/usr/local/bin/orc-helper event '{failureClusterAlias}' 'OrcPostMasterFailover' 'Failure type: {failureType}, new master: {successorHost}, slaves: {slaveHosts}' || true"
    PostIntermediateMasterFailoverProcesses:
      - "/usr/local/bin/orc-helper event '{failureClusterAlias}' 'OrcPostIntermediateMasterFailover' 'Failure type: {failureType}, failed hosts: {failedHost}, slaves: {countSlaves}' || true"

# PostGracefulTakeoverProcesses:
```



mysql cluster.yaml

```yaml
apiVersion: v1
data:
  ROOT_PASSWORD: YmlnZGF0YUAyMDIxCg==
kind: Secret
metadata:
  name: my-secret
type: Opaque

---
apiVersion: mysql.presslabs.org/v1alpha1
kind: MysqlCluster
metadata:
  name: mysql-cluster
spec:
  replicas: 3
  secretName: my-secret
  # image: percona:8.0

  mysqlVersion: "8.0"

  # initBucketURL: gs://bucket_name/backup.xtrabackup.gz
  # initBucketSecretName:

  ## PodDisruptionBudget
  # minAvailable: 1

  ## For recurrent backups set backupSchedule with a cronjob expression with seconds
  # backupSchedule:
  # backupURL: s3://bucket_name/
  # backupSecretName:
  # backupScheduleJobsHistoryLimit:
  # backupRemoteDeletePolicy:

  ## Custom Server ID Offset for replication
  # serverIDOffset: 100

  ## Configs that will be added to my.cnf for cluster
  # mysqlConf:
  #   innodb-buffer-size: 128M


  ## Specify additional pod specification
  # podSpec:
  #   imagePullSecrets: []
  #   labels: {}
  #   annotations: {}
  #   affinity:
  #     podAntiAffinity:
  #       preferredDuringSchedulingIgnoredDuringExecution:
  #         weight: 100
  #         podAffinityTerm:
  #           topologyKey: "kubernetes.io/hostname"
  #           labelSelector:
  #             matchlabels: <cluster-labels>
  #   backupAffinity: {}
  #   backupNodeSelector: {}
  #   backupPriorityClassName:
  #   backupTolerations: []
  #   # Override the default preStop hook with a custom command/script
  #   mysqlLifecycle:
  #     preStop:
  #       exec:
  #         command:
  #           - /scripts/demote-if-master
  #   nodeSelector: {}
  #   resources:
  #     requests:
  #       memory: 1G
  #       cpu:    200m
  #   tolerations: []
  #   priorityClassName:
  #   serviceAccountName: default
  #   # Use a initContainer to fix the permissons of a hostPath volume.
  #   initContainers:
  #     - name: volume-permissions
  #       image: busybox
  #       securityContext:
  #         runAsUser: 0
  #       command:
  #         - sh
  #         - -c
  #         - chmod 750 /data/mysql; chown 999:999 /data/mysql
  #       volumeMounts:
  #         - name: data
  #           mountPath: /data/mysql

  ## Specify additional volume specification
  volumeSpec:
    persistentVolumeClaim:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 5Gi
      storageClassName: "local-path"
  #   # https://godoc.org/k8s.io/api/core/v1#EmptyDirVolumeSource
  #   emptyDir: {}

  #   # https://godoc.org/k8s.io/api/core/v1#HostPathVolumeSource
  #   hostPath:
  #     path:
  #     type:


  ## Specify service objectives
  ## If thoses SLO are not fulfilled by cluster node then that node is
  ## removed from scheme
  # targetSLO:
  #   maxSlaveLatency: 10s

  ## You can use custom volume for /tmp partition if needed.
  ## Is disabled by default
  # tmpfsSize: 1Gi

  ## Set cluster in read only
  # readOnly: false

  ## Use `pigz` for parallel compression/decompression of backups
  ## Or specify any arbitrary compress/decompress commands with args
  # backupCompressCommand:
  #   - pigz
  #   - --stdout
  #
  # backupDecompressCommand:
  #   - pigz
  #   - --decompress

  ## Add metrics exporter extra arguments
  metricsExporterExtraArgs:
    - --collect.info_schema.userstats
    - --collect.perf_schema.file_events

  ## Add extra arguments to rclone
  # rcloneExtraArgs:
  #   - --buffer-size=1G
  #   - --multi-thread-streams=8
  #   - --retries-sleep=10s
  #   - --retries=10
  #   - --transfers=8
  #   - --s3-force-path-style=false # when use Alibaba OSS

  ## Add extra arguments to xbstream
  # xbstreamExtraArgs:
  #   - --parallel=8

  ## Add extra arguments to xtrabackup
  # xtrabackupExtraArgs:
  #   - --parallel=8

  ## Add extra arguments to xtrabackup during --prepare
  # xtrabackupPrepareExtraArgs:
  #   - --use-memory=5G

  ## Set xtrabackup target directory (the directory needs to exist)
  # xtrabackupTargetDir: /var/lib/mysql/.tmp/xtrabackup/

  # Add additional SQL commands to run during init of mysql
  # initFileExtraSQL:
  #   - "CREATE USER test@localhost"



```
