### ISSUE TITLE
MySQL container "can't create/write to file '/var/run/mysqld/mysqld.pid'

### ISSUE THREAD

**Issue by TomerG711** [bitpoke/mysql-operator#787]
After installing the operator, when I try creating mysqlcluster (using kubectl -f apply to YAML file, after creating the required secret with the root password), I get the following error in the container logs:

Can't create/write to file '/var/run/mysqld/mysqld.pid' (OS errno 13 - Permission denied)
 
I couldn't figure why there are no permissions.
I also tried looking for any place to config the runAsUser to 0 so the mysql container could run as root, however I didn't find anywhere.

How can it be fixed? Or where can I configure the mysql container user?

**Comment by calind** [comment]
The `fsGroup` is set in https://github.com/bitpoke/mysql-operator/blob/18a6031621733203b43374b835eaa2fe59d35795/pkg/controller/mysqlcluster/internal/syncer/statefullset.go#L132-L150

If there is a mismatch, means that percona changed user for their containers and we need to account for that in the operator.

As a workaround you should be able to mount `/var/run/mysqld` as a tmpfs, by specifying on `MySQLCluster`
 resource:

```yaml
spec:
  podSpec:
    volumeMounts:
    - mountPath: /var/run/mysqld
      name: var-run-mysqld
    volumes:
    - name: var-run-mysqld
      emptyDir:
        medium: Memory
```
