### ISSUE TITLE
mysqlConf with plugin-load-add

### ISSUE THREAD

**Issue by jiuker** [bitpoke/mysql-operator#792]
Version:latest
I set 
```
  mysqlConf:
      skip_ssl: 1
      plugin-load-add: "semisync_master.so;semisync_slave.so"
      rpl_semi_sync_master_enabled: 1
      rpl_semi_sync_master_timeout: 1000  # 1秒
      rpl_semi_sync_slave_enabled: 1
```

This version：
The resulting configMap has 'plugin-load-add = `semisync_ master.so; semisync_ slave. so`', but this MySQL starts with an error.([ERROR] Can't open shared library '/usr/lib/mysql/plugin/`semisync_master.so')
 If you remove the quotation marks, MySQL will start correctly. This is because 'ini', a third-party package, contains values byte ';' automatic quotation marks. 
Hope:
I wish I could add a mysqlStaticConf field and leave the configuration as it is.Because the keys of some values can be set repeatedly。
