### ISSUE TITLE
Cannot change mysql config by modify configMap

### ISSUE THREAD

**Issue by hellyhe** [bitpoke/mysql-operator#797]
kubernetes ver: 1.23
operator version:  v0.6.2
mysql ver 5.7 or 8.0

when use  _**kubectl edit cm my-cluster-mysql**_ to change mysql config, mysql pod will be recreate. 
but my configmap has no change when I run  kubectl edit cm  onece again.
check variables in mysql  with show global variables, get the same result.

cluster.yaml
```
apiVersion: mysql.presslabs.org/v1alpha1
kind: MysqlCluster
metadata:
  name: my-cluster
spec:
  replicas: 2
  secretName: my-cluster-secret

  mysqlConf:
    expire-logs-days: 7
    max-allowed-packet: 128M
    lower-case-table-names: 1
    max-binlog-size: 256M
    binlog-cache-size: 1M

  volumeSpec:
    persistentVolumeClaim:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 10Gi
---
apiVersion: v1
kind: Secret
metadata:
  name: my-cluster-secret
type: Opaque
data:
  ROOT_PASSWORD: cGFzc3dvcmQ=
```

**Comment by elrondwong** [comment]
The my-cluster-mysql cm is managed  by the operator, so you changes is refreshed by the operator. you should modify the CR of the mysqlCluster.

```yaml
kind: MysqlCluster
spec:
  mysqlConf:
    innodb-buffer-size: 128M
```
