### ISSUE TITLE
Cannot setup DigitalOcean Space S3-backups

### ISSUE THREAD

**Issue by LvLs9** [bitpoke/mysql-operator#813]
Hi! Do anyone have success with setting up Digital Ocean backups?

There is my cluster config:
```
backupSchedule: "0,10,20,30,40,50 * * * *"
backupSecretName: digitalocean-backup
backupURL: s3://test-k8s-mysql-backups
storageSize: 10G
```

And secret:
```
metadata:
  name: digitalocean-backup
spec:
  stringData:
    AWS_ACCESS_KEY_ID: <keyid>
    AWS_SECRET_ACCESS_KEY: <secretkey>
    AWS_REGION: fra1
    S3_PROVIDER: AWS
    S3_ENDPOINT: fra1.digitaloceanspaces.com
```

What I see in logs:
```
NoCredentialProviders: no valid providers in chain. Deprecated. 
For verbose messaging see aws.Config.CredentialsChainVerboseErrors
```
