### ISSUE TITLE
Updated password only take effect after 2min

### ISSUE THREAD

**Issue by drivebyer** [bitpoke/mysql-operator#848]
Step 1: create file test.yaml(then apply):
```YAML
apiVersion: mysql.presslabs.org/v1alpha1
kind: MysqlDatabase
metadata:
  name: test-database
  namespace: default
spec:
  database: test
  characterSet: utf8
  clusterRef:
    name: test-my-b
    namespace: default
---
apiVersion: mysql.presslabs.org/v1alpha1
kind: MysqlUser
metadata:
  name: test-user
  namespace: default
spec:
  user: test
  clusterRef:
    name: test-my-b
    namespace: default
  password:
    name: test-db-secret
    key: PASSWORD
  allowedHosts:
    - '%'
  permissions:
    - schema: test
      tables: ["*"]
      permissions:
        - ALL
---
apiVersion: v1
kind: Secret
metadata:
  name: test-db-secret
  namespace: default
data:
  DATABASE: dGVzdA==
  PASSWORD: dGVzdA==
  USERNAME: dGVzdA==
```
the database and use will be created.

Step 2: update data.PADDWORD of test-db-secret in test.yaml(then apply) 

We can connect to database with new password after 2min. I think the key code is:
https://github.com/bitpoke/mysql-operator/blob/42e15e6da8e0b83114c03f41a4a0b668a162d204/pkg/controller/mysqluser/mysqluser_controller.go#L108-L111

Maybe we should watch secret recourse to update password as soon as possiable.
