### ISSUE TITLE
MySQL Config: sql_mode - not getting set correctly

### ISSUE THREAD

**Issue by voarsh2** [bitpoke/mysql-operator#878]
Tried to set sql-mode: ''
And I see in my my.cnf the following:
```
sql-mode                       = STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_VALUE_ON_ZERO,NO_ENGINE_SUBSTITUTION,NO_ZERO_DATE,NO_ZERO_IN_DATE,ONLY_FULL_GROUP_BY
```
and:
```
sql_mode                       = 
```
At the bottom. I just want it set to nothing.
My Cluster config:
```
spec:
  mysqlConf:
    sql_mode: ''
  mysqlVersion: '8.0'
```
