### ISSUE TITLE
Use environment variables instead of k8s secret for passwords

### ISSUE THREAD

**Issue by chrism417** [bitpoke/mysql-operator#902]
When deploying the cluster, is there some other way to set the password for the root/app user other than a k8s secret?  

The only place I see to set the passwords are here: https://github.com/bitpoke/mysql-operator/blob/master/deploy/charts/mysql-cluster/values.yaml#L14-L17 which requires a kubernetes secret. 

For example, is there a way to use a ` SecretProviderClass`?

**Comment by zozidalom** [comment]
I don't know about an option for this unfortunately, but the workaround I found was this:

In Gitlab CI/CD to use an environment variable to setup the config I use helmfile and I created a _File type CI/CD variable_ for the values.yaml file of my chart which contains my mysql-cluster. 

Then in the secret I just read the variables from the values.yaml file.

```
apiVersion: v1
kind: Secret
metadata:
  name: my-mysql
type: Opaque
data:
  ROOT_PASSWORD: {{ .Values.rootPassword | b64enc }}
  DATABASE: {{ .Values.database | b64enc }}
  USER: {{ .Values.user | b64enc }}
  PASSWORD: {{ .Values.password | b64enc }}
```
